app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'app'
urlpatterns = [
     path('', views.index, name='index'),
     path('signup/', views.signup, name='signup'), # 追加 

     path('login/',
         auth_views.LoginView.as_view(template_name='app/login.html'),
         name='login'),
     path('logout/', auth_views.LogoutView.as_view(), name='logout'),
     path('product/<int:product_id>/', views.detail, name='detail'),
     path('fav_products/', views.fav_products, name='fav_products'),
     path('toggle_fav_product_status/', views.toggle_fav_product_status,
         name='toggle_fav_product_status'),
     path('cart/', views.cart, name='cart'),
     path('change_item_amount/', views.change_item_amount, name='change_item_amount'), # 追加
     path('order_history/', views.order_history, name='order_history'),

]

irodasday6/urls.py
from django.contrib import admin
from django.urls import path, include # 追加
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

app/templates/app/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html>
<head>
    <title>Djamazon</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
       <div class="container">
           <h1><a href="{% url 'app:index' %}">Djamazon</a></h1>
           <div class="header-menu">

               {% if request.user.is_authenticated %}
                  <span>Point: {{ user.point | intcomma }}</span> 
                  <span><a href="{% url 'app:fav_products' %}">お気に入り</a></span> 
                  <span><a href="{% url 'app:cart' %}">カート</a></span>    
                  <span><a href="{% url 'app:order_history' %}">注文履歴</a></span>
                  <span><a href="{% url 'app:logout' %}">ログアウト</a></span>
               {% else %}
                  <span><a href="{% url 'app:login' %}">ログイン</a></span>
                  <span><a href="{% url 'app:signup' %}">新規登録</a></span>
               {% endif %}
           </div>
       </div>
    </header>
    <div class="container">
       {% for message in messages %}
           <p class="message-{{ message.tags }}">{{ message }}</p>
       {% endfor %}
       {% block content %}{% endblock %}
    </div>
</body>
</html>

app/templates/app/cart.html
{% extends 'app/base.html' %}
{% load humanize %}
{% load filters %}

{% block content %}

<div class="cart">

<h2>カート</h2>
    <div class="purchase-form">
        <form action="{% url 'app:cart' %}" method="post">{% csrf_token %}
        <div class="purchase-form-container">
        <div class="purchase-form-address">
            <div>
            {{ purchase_form.non_field_errors }}
            {{ purchase_form.zip_code.label_tag }}
            {{ purchase_form.zip_code }}
            <input type="submit" name="search_address" value="住所を検索"/>
            <span>{{ purchase_form.zip_code.help_text }}</span>
            </div>
            <div>
            {{ purchase_form.address.label_tag }}
            {{ purchase_form.address }}
            </div>
        </div>
        <div class="purchase-form-pay">
         請求額:{{ total_price | intcomma }}
            <input type="submit" name="buy_product" class="purchase-button" value="購入する" /> 
        </div>
        </div>
        </form>
    </div>

  {% for product, num in cart_products.items %}
    <div class="order-item">
     <div class="order-item-image">
       <a href="{% url 'app:detail' product.id %}">
         <img src="{{ product.image.url }}" class="product-img">
       </a> 
     </div>
     <div class="order-item-info">
       <h2>{{ product.name }}</h2>
       <div>価格:<span class="info-value">{{ product.price | intcomma }}</span></div>
       <div>個数:<span class="info-value">{{ num | intcomma }}</span></div>
       <hr>
       <div>小計:<span class="info-value">{% multiply product.price num %}</span></div>
       <div class="order-item-amount-form">
        <form action="{% url 'app:change_item_amount' %}" method="post">{%csrf_token %}
            <input type="hidden" name="product_id" value="{{ product.id }}">
            <input type="submit" name="action_remove" value="一つ減らす" />
            <input type="submit" name="action_add" value="一つ増やす" /> 
        </form>
       </div> 
     </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

app/templates/app/detail.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block content %}
<div class="product-detail">
  <div class="product-detail-image">
    <img src="{{ product.image.url }}" class="product-img">
  </div>

  <div class="product-detail-info">
    <h2>{{ product.name }}</h2>
    <hr>
  <div class="point-fav-section">
    <h4>{{ product.price | intcomma }}ポイント</h4> 
    {% if request.user.is_authenticated %}
      <form action="{% url 'app:toggle_fav_product_status' %}"
method="post">{% csrf_token %}
          <input type="hidden" name="product_id"
value="{{ product.id }}">
        {% if product in user.fav_products.all %}
          <input type="submit" name="submit" class="fav_button" value="
お気に入りから外す" /> 
        {% else %}
          <input type="submit" name="submit" class="fav_button" value=" お気に入りに入れる" />
        {% endif %}
      </form>
    {% endif %}
  </div>
  <p>{{ product.description }}</p>

    <div>
     {% if request.user.is_authenticated %}
       <form action="{% url 'app:detail' product.id %}"
method="post">{% csrf_token %}
        {{ add_to_cart_form.as_p }}
        <button class="purchase-button" type="submit">カートに追加する
</button>
       </form>
     {% else %}
       <a href="{% url 'app:login' %}?next={{ request.path }}"><button
class="purchase-button">ログインして購入する</button></a> 
     {% endif %}
    </div>

</div>    

</div>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block content %}
<!-- 以下を追加 -->
{% if 'fav_products' in request.path %}
<div style="font-weight:bold; font-size: 28px; margin-bottom: 20px;">
お気に入り商品
</div>
{% endif %}
<!-- 追加ここまで -->

<div class="product-container">
{% for product in products %}
    <div class="product">
       <a href="{% url 'app:detail' product.id %}">
           <img src="{{ product.image.url }}" class="product-img">
       </a>
       <div class="product-info">
           <div class="product-name">{{ product.name }}</div>
           <div class="product-price">Point: {{ product.price | intcomma }}</div>
       </div>
    </div>
{% endfor %}
</div>

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% block content %}
<form class="form-signin" method="post">{% csrf_token %}
    {% if form.errors %}
<p>ユーザー名かパスワードが間違っています。</p> 
    {% endif %}
<h2>ログイン</h2>
<label>メールアドレス</label>
<input name="username"> <!-- email ではない --> 
<br>
<label>パスワード</label>
<input type="password" name="password">
<br>
<input type="submit" value="ログイン">

</form>
{% endblock %}

app/templates/app/order_history.html
{% extends 'app/base.html' %}
{% load humanize %}

{% block content %}

<div class="order-history"> 

<h2>注文履歴</h2>

{% for sale in sales %}
  <div class="order-item">
    <div class="order-item-image">
     <a href="{% url 'app:detail' sale.product.id %}">
       <img src="{{ sale.product.image.url }}" class="product-img">
     </a>
    </div>
    <div class="order-item-info">
     <h2>{{ sale.product.name }}</h2>
     <div>価格:<span class="info-value">{{ sale.price | intcomma }}</span></div>
     <div>個数:<span class="info-value">{{ sale.amount | intcomma }}</span></div>
     <hr>
     <div>小計:<span class="info-value">{{ sale.total_price | intcomma }}</span></div>
     <span class="info-timestamp">{{ sale.created_at | date:"Y/m/d" }}</span>
    </div>
  </div>
{% endfor %}

</div>
{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}
{% block content %}
<h2>ユーザー登録</h2>
<form method="post" action="{% url 'app:signup' %}">
{% csrf_token %}
<label>メールアドレス</label> 
{{ form.email }}
{{ form.email.errors }} 
<br> 
<label>パスワード</label>
{{ form.password1 }}
{{ form.password1.errors }}
<br>
<label>パスワード(確認)</label>
{{ form.password2 }}
{{ form.password2.errors }}
<br>
<input type="submit" value="登録する">
</form>
{% endblock %}